version: '3.8'

services:
  unaspro_exporter:
    image: ghcr.io/jaykeegan/unas_pro_exporter:latest
    ports:
      - "9101:9101"
    environment:
      - DEBUG=false
      - PORT=9101
      - DEVICE_HOSTNAME=
      - DEVICE_USERNAME=
      - DEVICE_PASSWORD=
      - CHECK_FREQUENCY=5
